// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO "activity_logs" (
    "id",
    "organisation_id",
    "project_id",
    "entity_type",
    "entity_id",
    "action",
    "actor_id",
    "metadata"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, organisation_id, project_id, entity_type, entity_id, action, actor_id, metadata, created_at
`

type CreateActivityLogParams struct {
	ID             pgtype.UUID
	OrganisationID pgtype.UUID
	ProjectID      pgtype.UUID
	EntityType     ActivityEntityType
	EntityID       pgtype.UUID
	Action         ActivityAction
	ActorID        pgtype.UUID
	Metadata       []byte
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ID,
		arg.OrganisationID,
		arg.ProjectID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActorID,
		arg.Metadata,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.ActorID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityLogsByEntity = `-- name: ListActivityLogsByEntity :many
SELECT id, organisation_id, project_id, entity_type, entity_id, action, actor_id, metadata, created_at
FROM "activity_logs"
WHERE "entity_id" = $1
AND ("created_at" < $2::timestamp OR $2::timestamp IS NULL)
ORDER BY "created_at" DESC
LIMIT $3
`

type ListActivityLogsByEntityParams struct {
	EntityID pgtype.UUID
	Column2  pgtype.Timestamp
	Limit    int32
}

func (q *Queries) ListActivityLogsByEntity(ctx context.Context, arg ListActivityLogsByEntityParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByEntity, arg.EntityID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByOrg = `-- name: ListActivityLogsByOrg :many
SELECT id, organisation_id, project_id, entity_type, entity_id, action, actor_id, metadata, created_at
FROM "activity_logs"
WHERE "organisation_id" = $1
AND ("created_at" < $2::timestamp OR $2::timestamp IS NULL)
ORDER BY "created_at" DESC
LIMIT $3
`

type ListActivityLogsByOrgParams struct {
	OrganisationID pgtype.UUID
	Column2        pgtype.Timestamp
	Limit          int32
}

func (q *Queries) ListActivityLogsByOrg(ctx context.Context, arg ListActivityLogsByOrgParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByOrg, arg.OrganisationID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByProject = `-- name: ListActivityLogsByProject :many
SELECT id, organisation_id, project_id, entity_type, entity_id, action, actor_id, metadata, created_at
FROM "activity_logs"
WHERE "project_id" = $1
AND ("created_at" < $2::timestamp OR $2::timestamp IS NULL)
ORDER BY "created_at" DESC
LIMIT $3
`

type ListActivityLogsByProjectParams struct {
	ProjectID pgtype.UUID
	Column2   pgtype.Timestamp
	Limit     int32
}

func (q *Queries) ListActivityLogsByProject(ctx context.Context, arg ListActivityLogsByProjectParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByProject, arg.ProjectID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
