// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO "activity_logs" (
    "id",
    "action",
    "user_id",
    "project_id",
    "target_id",
    "timestamp"
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, action, user_id, project_id, target_id, timestamp
`

type CreateActivityLogParams struct {
	ID        pgtype.UUID
	Action    string
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	TargetID  pgtype.UUID
	Timestamp pgtype.Timestamp
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ID,
		arg.Action,
		arg.UserID,
		arg.ProjectID,
		arg.TargetID,
		arg.Timestamp,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.UserID,
		&i.ProjectID,
		&i.TargetID,
		&i.Timestamp,
	)
	return i, err
}

const listActivityLogsByProjectId = `-- name: ListActivityLogsByProjectId :many
SELECT id, action, user_id, project_id, target_id, timestamp
FROM "activity_logs"
WHERE "project_id" = $1
ORDER BY "timestamp" DESC
`

func (q *Queries) ListActivityLogsByProjectId(ctx context.Context, projectID pgtype.UUID) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.UserID,
			&i.ProjectID,
			&i.TargetID,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
