// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO "comments" (
    "id",
    "content",
    "author_id",
    "issue_id"
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, content, author_id, issue_id, created_at, updated_at
`

type CreateCommentParams struct {
	ID       pgtype.UUID
	Content  string
	AuthorID pgtype.UUID
	IssueID  pgtype.UUID
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.Content,
		arg.AuthorID,
		arg.IssueID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorID,
		&i.IssueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM "comments"
WHERE "id" = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentById = `-- name: GetCommentById :one
SELECT id, content, author_id, issue_id, created_at, updated_at
FROM "comments"
WHERE "id" = $1
`

func (q *Queries) GetCommentById(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentById, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorID,
		&i.IssueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByIssueId = `-- name: ListCommentsByIssueId :many
SELECT id, content, author_id, issue_id, created_at, updated_at
FROM "comments"
WHERE "issue_id" = $1
ORDER BY "created_at" ASC
`

func (q *Queries) ListCommentsByIssueId(ctx context.Context, issueID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByIssueId, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorID,
			&i.IssueID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE "comments"
SET
    "content" = $2,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, content, author_id, issue_id, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      pgtype.UUID
	Content string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorID,
		&i.IssueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
