// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE "invitations"
SET "accepted_at" = now()
WHERE "token" = $1
RETURNING id, email, organisation_id, role, token, invited_by, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrganisationID,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO "invitations" (
    "id",
    "email",
    "organisation_id",
    "role",
    "token",
    "invited_by",
    "expires_at"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, email, organisation_id, role, token, invited_by, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	ID             pgtype.UUID
	Email          string
	OrganisationID pgtype.UUID
	Role           MemberRole
	Token          string
	InvitedBy      pgtype.UUID
	ExpiresAt      pgtype.Timestamp
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.Email,
		arg.OrganisationID,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrganisationID,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :exec
DELETE FROM "invitations"
WHERE "expires_at" < now()
AND "accepted_at" IS NULL
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInvitations)
	return err
}

const getInvitationByEmailAndOrg = `-- name: GetInvitationByEmailAndOrg :one
SELECT id, email, organisation_id, role, token, invited_by, expires_at, accepted_at, created_at FROM "invitations"
WHERE "email" = $1
AND "organisation_id" = $2
AND "accepted_at" IS NULL
AND "expires_at" > now()
`

type GetInvitationByEmailAndOrgParams struct {
	Email          string
	OrganisationID pgtype.UUID
}

func (q *Queries) GetInvitationByEmailAndOrg(ctx context.Context, arg GetInvitationByEmailAndOrgParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByEmailAndOrg, arg.Email, arg.OrganisationID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrganisationID,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, email, organisation_id, role, token, invited_by, expires_at, accepted_at, created_at FROM "invitations"
WHERE "token" = $1
AND "accepted_at" IS NULL
AND "expires_at" > now()
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrganisationID,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}
