// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO "issues" (
    "id",
    "title",
    "description",
    "status",
    "priority",
    "project_id",
    "reporter_id",
    "assignee_id"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, description, status, priority, project_id, reporter_id, assignee_id, created_at, updated_at
`

type CreateIssueParams struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      string
	Priority    string
	ProjectID   pgtype.UUID
	ReporterID  pgtype.UUID
	AssigneeID  pgtype.UUID
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ProjectID,
		arg.ReporterID,
		arg.AssigneeID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ProjectID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM "issues"
WHERE "id" = $1
`

func (q *Queries) DeleteIssue(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIssue, id)
	return err
}

const getIssueById = `-- name: GetIssueById :one
SELECT id, title, description, status, priority, project_id, reporter_id, assignee_id, created_at, updated_at
FROM "issues"
WHERE "id" = $1
`

func (q *Queries) GetIssueById(ctx context.Context, id pgtype.UUID) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueById, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ProjectID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssuesByProject = `-- name: ListIssuesByProject :many
SELECT id, title, description, status, priority, project_id, reporter_id, assignee_id, created_at, updated_at
FROM "issues"
WHERE "project_id" = $1
ORDER BY "created_at" DESC
`

func (q *Queries) ListIssuesByProject(ctx context.Context, projectID pgtype.UUID) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ProjectID,
			&i.ReporterID,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE "issues"
SET
    "title" = $2,
    "description" = $3,
    "status" = $4,
    "priority" = $5,
    "assignee_id" = $6,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, title, description, status, priority, project_id, reporter_id, assignee_id, created_at, updated_at
`

type UpdateIssueParams struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      string
	Priority    string
	AssigneeID  pgtype.UUID
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ProjectID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
