// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO "members" (
    "id",
    "role",
    "user_id",
    "organisation_id"
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, role, user_id, organisation_id, created_at, updated_at
`

type CreateMemberParams struct {
	ID             pgtype.UUID
	Role           MemberRole
	UserID         pgtype.UUID
	OrganisationID pgtype.UUID
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.Role,
		arg.UserID,
		arg.OrganisationID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.UserID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM "members"
WHERE "id" = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMemberById = `-- name: GetMemberById :one
SELECT id, role, user_id, organisation_id, created_at, updated_at
FROM "members"
WHERE "id" = $1
`

func (q *Queries) GetMemberById(ctx context.Context, id pgtype.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberById, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.UserID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByUserAndOrg = `-- name: GetMemberByUserAndOrg :one
SELECT id, role, user_id, organisation_id, created_at, updated_at
FROM "members"
WHERE "user_id" = $1
  AND "organisation_id" = $2
`

type GetMemberByUserAndOrgParams struct {
	UserID         pgtype.UUID
	OrganisationID pgtype.UUID
}

func (q *Queries) GetMemberByUserAndOrg(ctx context.Context, arg GetMemberByUserAndOrgParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByUserAndOrg, arg.UserID, arg.OrganisationID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.UserID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMember = `-- name: UpdateMember :one
UPDATE "members"
SET
    "role" = $2,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, role, user_id, organisation_id, created_at, updated_at
`

type UpdateMemberParams struct {
	ID   pgtype.UUID
	Role MemberRole
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember, arg.ID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.UserID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
