// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityAction string

const (
	ActivityActionCREATED         ActivityAction = "CREATED"
	ActivityActionUPDATED         ActivityAction = "UPDATED"
	ActivityActionDELETED         ActivityAction = "DELETED"
	ActivityActionSTATUSCHANGED   ActivityAction = "STATUS_CHANGED"
	ActivityActionPRIORITYCHANGED ActivityAction = "PRIORITY_CHANGED"
	ActivityActionASSIGNED        ActivityAction = "ASSIGNED"
	ActivityActionUNASSIGNED      ActivityAction = "UNASSIGNED"
	ActivityActionROLECHANGED     ActivityAction = "ROLE_CHANGED"
	ActivityActionMEMBERJOINED    ActivityAction = "MEMBER_JOINED"
	ActivityActionMEMBERLEFT      ActivityAction = "MEMBER_LEFT"
	ActivityActionMEMBERREMOVED   ActivityAction = "MEMBER_REMOVED"
)

func (e *ActivityAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityAction(s)
	case string:
		*e = ActivityAction(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityAction: %T", src)
	}
	return nil
}

type NullActivityAction struct {
	ActivityAction ActivityAction
	Valid          bool // Valid is true if ActivityAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityAction) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityAction), nil
}

type ActivityEntityType string

const (
	ActivityEntityTypeISSUE        ActivityEntityType = "ISSUE"
	ActivityEntityTypePROJECT      ActivityEntityType = "PROJECT"
	ActivityEntityTypeMEMBER       ActivityEntityType = "MEMBER"
	ActivityEntityTypeORGANISATION ActivityEntityType = "ORGANISATION"
)

func (e *ActivityEntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityEntityType(s)
	case string:
		*e = ActivityEntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityEntityType: %T", src)
	}
	return nil
}

type NullActivityEntityType struct {
	ActivityEntityType ActivityEntityType
	Valid              bool // Valid is true if ActivityEntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityEntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityEntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityEntityType), nil
}

type IssuePriority string

const (
	IssuePriorityNOPRIORITY IssuePriority = "NO_PRIORITY"
	IssuePriorityLOW        IssuePriority = "LOW"
	IssuePriorityMEDIUM     IssuePriority = "MEDIUM"
	IssuePriorityHIGH       IssuePriority = "HIGH"
)

func (e *IssuePriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssuePriority(s)
	case string:
		*e = IssuePriority(s)
	default:
		return fmt.Errorf("unsupported scan type for IssuePriority: %T", src)
	}
	return nil
}

type NullIssuePriority struct {
	IssuePriority IssuePriority
	Valid         bool // Valid is true if IssuePriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssuePriority) Scan(value interface{}) error {
	if value == nil {
		ns.IssuePriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssuePriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssuePriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssuePriority), nil
}

type IssueStatus string

const (
	IssueStatusBACKLOG    IssueStatus = "BACKLOG"
	IssueStatusTODO       IssueStatus = "TODO"
	IssueStatusINPROGRESS IssueStatus = "IN_PROGRESS"
	IssueStatusINREVIEW   IssueStatus = "IN_REVIEW"
	IssueStatusDONE       IssueStatus = "DONE"
	IssueStatusCANCELLED  IssueStatus = "CANCELLED"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus
	Valid       bool // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type MemberRole string

const (
	MemberRoleOWNER  MemberRole = "OWNER"
	MemberRoleADMIN  MemberRole = "ADMIN"
	MemberRoleMEMBER MemberRole = "MEMBER"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type ActivityLog struct {
	ID             pgtype.UUID
	OrganisationID pgtype.UUID
	ProjectID      pgtype.UUID
	EntityType     ActivityEntityType
	EntityID       pgtype.UUID
	Action         ActivityAction
	ActorID        pgtype.UUID
	Metadata       []byte
	CreatedAt      pgtype.Timestamp
}

type Comment struct {
	ID        pgtype.UUID
	Content   string
	AuthorID  pgtype.UUID
	IssueID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Invitation struct {
	ID             pgtype.UUID
	Email          string
	OrganisationID pgtype.UUID
	Role           MemberRole
	Token          string
	InvitedBy      pgtype.UUID
	ExpiresAt      pgtype.Timestamp
	AcceptedAt     pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}

type Issue struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      IssueStatus
	Priority    IssuePriority
	ProjectID   pgtype.UUID
	ReporterID  pgtype.UUID
	AssigneeID  pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Member struct {
	ID             pgtype.UUID
	Role           MemberRole
	UserID         pgtype.UUID
	OrganisationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Organisation struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Project struct {
	ID             pgtype.UUID
	Name           string
	Description    pgtype.Text
	OrganisationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
