// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID        pgtype.UUID
	Action    string
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	TargetID  pgtype.UUID
	Timestamp pgtype.Timestamp
}

type Comment struct {
	ID        pgtype.UUID
	Content   string
	AuthorID  pgtype.UUID
	IssueID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Issue struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      string
	Priority    string
	ProjectID   pgtype.UUID
	ReporterID  pgtype.UUID
	AssigneeID  pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Member struct {
	ID             pgtype.UUID
	Role           string
	UserID         pgtype.UUID
	OrganisationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Organisation struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Project struct {
	ID             pgtype.UUID
	Name           string
	Description    pgtype.Text
	OrganisationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
