// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MemberRole string

const (
	MemberRoleOWNER  MemberRole = "OWNER"
	MemberRoleADMIN  MemberRole = "ADMIN"
	MemberRoleMEMBER MemberRole = "MEMBER"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type ActivityLog struct {
	ID        pgtype.UUID
	Action    string
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	TargetID  pgtype.UUID
	Timestamp pgtype.Timestamp
}

type Comment struct {
	ID        pgtype.UUID
	Content   string
	AuthorID  pgtype.UUID
	IssueID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Issue struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      string
	Priority    string
	ProjectID   pgtype.UUID
	ReporterID  pgtype.UUID
	AssigneeID  pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Member struct {
	ID             pgtype.UUID
	Role           MemberRole
	UserID         pgtype.UUID
	OrganisationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Organisation struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Project struct {
	ID             pgtype.UUID
	Name           string
	Description    pgtype.Text
	OrganisationID pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
