// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organisations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO "organisations" (
    "id",
    "name",
    "owner_id"
) VALUES (
    $1, $2, $3
)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateOrganisationParams struct {
	ID      pgtype.UUID
	Name    string
	OwnerID pgtype.UUID
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation, arg.ID, arg.Name, arg.OwnerID)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganisation = `-- name: DeleteOrganisation :exec
DELETE FROM "organisations"
WHERE "id" = $1
`

func (q *Queries) DeleteOrganisation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganisation, id)
	return err
}

const getOrganisationById = `-- name: GetOrganisationById :one
SELECT id, name, owner_id, created_at, updated_at
FROM "organisations"
WHERE "id" = $1
`

func (q *Queries) GetOrganisationById(ctx context.Context, id pgtype.UUID) (Organisation, error) {
	row := q.db.QueryRow(ctx, getOrganisationById, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganisationsByUser = `-- name: GetOrganisationsByUser :many
SELECT o.id, o.name, o.owner_id, o.created_at, o.updated_at
FROM "organisations" o
INNER JOIN "members" m ON m.organisation_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at DESC
`

func (q *Queries) GetOrganisationsByUser(ctx context.Context, userID pgtype.UUID) ([]Organisation, error) {
	rows, err := q.db.Query(ctx, getOrganisationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organisation
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisation = `-- name: UpdateOrganisation :one
UPDATE "organisations"
SET
    "name" = $2,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, name, owner_id, created_at, updated_at
`

type UpdateOrganisationParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, updateOrganisation, arg.ID, arg.Name)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
