// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO "projects" (
    "id",
    "name",
    "description",
    "organisation_id"
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, description, organisation_id, created_at, updated_at
`

type CreateProjectParams struct {
	ID             pgtype.UUID
	Name           string
	Description    pgtype.Text
	OrganisationID pgtype.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OrganisationID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM "projects"
WHERE "id" = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, name, description, organisation_id, created_at, updated_at
FROM "projects"
WHERE "id" = $1
`

func (q *Queries) GetProjectById(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectsByOrganisation = `-- name: GetProjectsByOrganisation :many
SELECT id, name, description, organisation_id, created_at, updated_at
FROM "projects"
WHERE "organisation_id" = $1
ORDER BY "created_at" DESC
`

func (q *Queries) GetProjectsByOrganisation(ctx context.Context, organisationID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOrganisation, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OrganisationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE "projects"
SET
    "name" = $2,
    "description" = $3,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, name, description, organisation_id, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
